[app]
runMode = "dev"
name = "webapp"
port = 8080
// logger
logProvider = "file"
logPath = "/tmp"
logRotate = true
logRotateType = "day"
logLimit = "100MB"
logExt = "log"

[mysql_manager]
init = true
ping = false

[redis_manager]
init = true
ping = false

[[mysql]]
name="master"
host="localhost"
port=3306
user="root"
db="test"
password=""
read_only=false

[[mysql]]
name="slave-01"
host="localhost"
port=3306
user="root"
db="test"
password=""
read_only=true

[redis]
host="localhost"
port= 6379
db = 0
password = ""
ping = false