[app]
runMode = "dev"
name = "grpc-hello"
port = 28080

logProvider = "file"
logPath = "/tmp"
logRotate = true
logRotateType = "day"
logLimit = "100MB"

[mysql_manager]
ping = false

[[mysql]]
name="master"
host="localhost"
port=3306
user="root"
db="test"
password=""
read_only=false

[redis]
host="localhost"
port= 6379
db = 0
ping = false
